---
- hosts: webservers
  become: true
  become_user: root

  tasks:

#install ngins on the server
    - name: install nginx
      apt:
        name: nginx
        state: latest

#change the default configurations of nginx    
    - name: change nginx default content
      ansible.builtin.blockinfile:
        path: /etc/nginx/sites-available/default
        marker: "{mark}"
        marker_begin: "server {"
        marker_end: "}"
        block: |-
            listen 8080 default_server;
              listen [::]:8080 default_server;
              location / {
                proxy_pass http://localhost:8081;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection keep-alive;
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
              }

# #get installation file of nodejs 14    
#     - name: get nodejs 14 installation
#       shell: |
#         curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - name: Download file and force basic auth
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_14.x
        dest: /tmp/node14.sh

    - name: pm2 package
      become: true
      become_user: root
      shell: |
        sudo /tmp/node14.sh 

#install nodejs 14
    - name: "Install nodejs"
      become: true
      become_user: root
      apt:
        update_cache: yes
        name: nodejs
        state: present 

#initialize db 
    - name: init-db
      become: true
      become_user: root
      shell: |
        cd /home/ubuntu/bootcamp-app/Job1/s
        sudo npm run initdb

#configure pm2 service for app
    - name: pm2 package
      become: true
      become_user: root
      shell: |
        cd /home/ubuntu/bootcamp-app/Job1/s
        sudo npm install pm2 -g
        sudo pm2 start /home/ubuntu/bootcamp-app/Job1/s/src/index.js
        sudo pm2 startup ubuntu
        
#restart nginx service
    - name: restart nginx
      service: 
        name: nginx
        enabled: yes
        state: restarted

  
    
